# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /work/poky/meta \
  /work/poky/meta-poky \
  /work/poky/meta-yocto-bsp \
  /work/poky/meta-raspberrypi \
  /work/poky/meta-openembedded/meta-oe \
  /work/poky/meta-amit \
  /work/poky/meta-qt5 \
  /work/poky/meta-observability \
  "
