BBPATH .= ":${LAYERDIR}"

BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "observability"
BBFILE_PATTERN_observability = "^${LAYERDIR}/"
BBFILE_PRIORITY_observability = "6"

LAYERDEPENDS_observability = "core"
LAYERSERIES_COMPAT_observability = "kirkstone"
